### ISSUE TITLE
Text not wrapping in index page tables

### ISSUE THREAD

**Issue by isaacmast** [brucrew/brucrew#17]
Some of the columns in the tables in the index page display the text in a single line, causing the tables to be of an unnecessarily long length. The columns that cause this problem are the Description, Location, and My Job columns in the projects table, as well as the Project Description column in the recent hours table. The text in these columns should wrap within the cell to prevent the tables from becoming excessively long horizontally.

**Comment by brucrew** [comment]
Issue fixed by Isaac
